In [128]:
import pandas as pd
import seaborn as sns
import numpy as np

In [129]:
data = pd.read_excel("./Downloads/netflix_data.xlsx")

In [130]:
data

N_id                           Title Main Genre  \
0       215309      Ace Ventura: Pet Detective     Comedy   
1       215318  Ace Ventura: When Nature Calls     Comedy   
2       217258               The Addams Family     Comedy   
3       217303            Addams Family Values     Comedy   
4       235527                       Agneepath      Drama   
...        ...                             ...        ...   
6398  81988312                     Laila Majnu    Romance   
6399  81988313                Veere Di Wedding     Comedy   
6400  81992621    Paw Patrol Holiday Fireplace       Kids   
6401  81994051                        Notebook      Drama   
6402  81994054                       Loveyatri    Romance   

                                             Sub Genres  Release Year  \
0                                   Comedy, Mystery, US        1994.0   
1                        Comedy, Action & Adventure, US        1995.0   
2                                            Comedy, US        1991.0   
3                                            Comedy, US        1993.0   
4               Hindi-Language, Bollywood, Crime, Drama        1990.0   
...                                                 ...           ...   
6398  Hindi-Language, Bollywood, Drama, Romantic, Ba...        2018.0   
6399                  Hindi-Language, Bollywood, Comedy        2018.0   
6400                       Kids Music, Special Interest        2024.0   
6401  Hindi-Language, Bollywood, Drama, Romantic, So...        2019.0   
6402         Hindi-Language, Bollywood, Drama, Romantic        2018.0   

     Maturity Rating                                     Original Audio  \
0                  A                          Hindi, English [Original]   
1            U/A 16+                          Hindi, English [Original]   
2            U/A 13+  English [Original], Hindi, English - Audio Des...   
3            U/A 13+  English [Original], Hindi, English - Audio Des...   
4            U/A 16+                                   Hindi [Original]   
...              ...                                                ...   
6398         U/A 13+                                   Hindi [Original]   
6399         U/A 16+                                   Hindi [Original]   
6400               U                             No Dialogue [Original]   
6401          U/A 7+                                   Hindi [Original]   
6402          U/A 7+                                   Hindi [Original]   

                                        Recommendations  
0     70184054, 60001650, 70112729, 70027007, 115246...  
1     70184054, 60001650, 70112729, 70027007, 115246...  
2     81156676, 81231974, 70027007, 80049939, 702179...  
3     81156676, 70044593, 81231974, 70027007, 800500...  
4     17517355, 80158546, 80158395, 80074065, 702042...  
...                                                 ...  
6398  80065328, 81994054, 80087743, 81423081, 819940...  
6399  70181653, 80065328, 81672746, 80032081, 703034...  
6400  81294811, 81154166, 81272431, 81640914, 815003...  
6401  80080110, 80065328, 81994054, 80087743, 819883...  
6402  80080110, 80065328, 81988312, 70303428, 800877...  

[6403 rows x 8 columns]

In [131]:
data.columns

Index(['N_id', 'Title', 'Main Genre', 'Sub Genres', 'Release Year',
       'Maturity Rating', 'Original Audio', 'Recommendations'],
      dtype='object')

In [132]:
data = data.drop('Recommendations',axis=1)
data.head()

N_id                           Title Main Genre  \
0  215309      Ace Ventura: Pet Detective     Comedy   
1  215318  Ace Ventura: When Nature Calls     Comedy   
2  217258               The Addams Family     Comedy   
3  217303            Addams Family Values     Comedy   
4  235527                       Agneepath      Drama   

                                Sub Genres  Release Year Maturity Rating  \
0                      Comedy, Mystery, US        1994.0               A   
1           Comedy, Action & Adventure, US        1995.0         U/A 16+   
2                               Comedy, US        1991.0         U/A 13+   
3                               Comedy, US        1993.0         U/A 13+   
4  Hindi-Language, Bollywood, Crime, Drama        1990.0         U/A 16+   

                                      Original Audio  
0                          Hindi, English [Original]  
1                          Hindi, English [Original]  
2  English [Original], Hindi, English - Audio Des...  
3  English [Original], Hindi, English - Audio Des...  
4                                   Hindi [Original]

In [133]:
data['tokens'] = data['Title'] + ' '+ data['Main Genre'] + ' ' +  data['Sub Genres'] + ' ' + data['Original Audio']
data.head()

N_id                           Title Main Genre  \
0  215309      Ace Ventura: Pet Detective     Comedy   
1  215318  Ace Ventura: When Nature Calls     Comedy   
2  217258               The Addams Family     Comedy   
3  217303            Addams Family Values     Comedy   
4  235527                       Agneepath      Drama   

                                Sub Genres  Release Year Maturity Rating  \
0                      Comedy, Mystery, US        1994.0               A   
1           Comedy, Action & Adventure, US        1995.0         U/A 16+   
2                               Comedy, US        1991.0         U/A 13+   
3                               Comedy, US        1993.0         U/A 13+   
4  Hindi-Language, Bollywood, Crime, Drama        1990.0         U/A 16+   

                                      Original Audio  \
0                          Hindi, English [Original]   
1                          Hindi, English [Original]   
2  English [Original], Hindi, English - Audio Des...   
3  English [Original], Hindi, English - Audio Des...   
4                                   Hindi [Original]   

                                              tokens  
0  Ace Ventura: Pet Detective Comedy Comedy, Myst...  
1  Ace Ventura: When Nature Calls Comedy Comedy, ...  
2  The Addams Family Comedy Comedy, US English [O...  
3  Addams Family Values Comedy Comedy, US English...  
4  Agneepath Drama Hindi-Language, Bollywood, Cri...

In [134]:
data = data.drop(['Main Genre','Sub Genres', 'Original Audio'], axis=1)

In [135]:
import sklearn as sklearn

In [136]:
from sklearn.preprocessing import LabelEncoder as le

In [137]:
le = le()

In [138]:
data['Maturity Rating'] = le.fit_transform(data['Maturity Rating'])

In [139]:
data.head(2)

N_id                           Title  Release Year  Maturity Rating  \
0  215309      Ace Ventura: Pet Detective        1994.0                0   
1  215318  Ace Ventura: When Nature Calls        1995.0                3   

                                              tokens  
0  Ace Ventura: Pet Detective Comedy Comedy, Myst...  
1  Ace Ventura: When Nature Calls Comedy Comedy, ...

In [140]:
data['Maturity Rating'].values

array([0, 3, 2, ..., 1, 4, 4])

In [141]:
data.dropna(inplace=True)

In [142]:
data.head(1)

N_id                       Title  Release Year  Maturity Rating  \
0  215309  Ace Ventura: Pet Detective        1994.0                0   

                                              tokens  
0  Ace Ventura: Pet Detective Comedy Comedy, Myst...

In [143]:
data['Release Year'] = data['Release Year'].astype(int)

In [144]:
data.head(1)

N_id                       Title  Release Year  Maturity Rating  \
0  215309  Ace Ventura: Pet Detective          1994                0   

                                              tokens  
0  Ace Ventura: Pet Detective Comedy Comedy, Myst...

In [145]:
data['AllWords'] =  data['Release Year'].astype(str) + ' ' + data['Maturity Rating'].astype(str) + ' ' + data['tokens']
data.head()

N_id                           Title  Release Year  Maturity Rating  \
0  215309      Ace Ventura: Pet Detective          1994                0   
1  215318  Ace Ventura: When Nature Calls          1995                3   
2  217258               The Addams Family          1991                2   
3  217303            Addams Family Values          1993                2   
4  235527                       Agneepath          1990                3   

                                              tokens  \
0  Ace Ventura: Pet Detective Comedy Comedy, Myst...   
1  Ace Ventura: When Nature Calls Comedy Comedy, ...   
2  The Addams Family Comedy Comedy, US English [O...   
3  Addams Family Values Comedy Comedy, US English...   
4  Agneepath Drama Hindi-Language, Bollywood, Cri...   

                                            AllWords  
0  1994 0 Ace Ventura: Pet Detective Comedy Comed...  
1  1995 3 Ace Ventura: When Nature Calls Comedy C...  
2  1991 2 The Addams Family Comedy Comedy, US Eng...  
3  1993 2 Addams Family Values Comedy Comedy, US ...  
4  1990 3 Agneepath Drama Hindi-Language, Bollywo...

In [146]:
data = data.drop(['Release Year', 'Maturity Rating','tokens'], axis = 1)

In [147]:
data.head()

N_id                           Title  \
0  215309      Ace Ventura: Pet Detective   
1  215318  Ace Ventura: When Nature Calls   
2  217258               The Addams Family   
3  217303            Addams Family Values   
4  235527                       Agneepath   

                                            AllWords  
0  1994 0 Ace Ventura: Pet Detective Comedy Comed...  
1  1995 3 Ace Ventura: When Nature Calls Comedy C...  
2  1991 2 The Addams Family Comedy Comedy, US Eng...  
3  1993 2 Addams Family Values Comedy Comedy, US ...  
4  1990 3 Agneepath Drama Hindi-Language, Bollywo...

In [150]:
data.shape

(3767, 3)

In [124]:
!pip install nltk

In [162]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features = 3000)

vectors = cv.fit_transform(data['AllWords'])

In [163]:
vectors.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [164]:
print(cv.get_feature_names_out())

['10' '100' '11' ... 'ìjọ' 'ñera' 'òlòtūré']


In [165]:
import nltk

In [166]:
from nltk.stem.porter import PorterStemmer

In [167]:
ps = PorterStemmer()

In [170]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)


In [171]:
data['AllWords'].apply(stem)

0       1994 0 ace ventura: pet detect comedi comedy, ...
1       1995 3 ace ventura: when natur call comedi com...
2       1991 2 the addam famili comedi comedy, us engl...
3       1993 2 addam famili valu comedi comedy, us eng...
4       1990 3 agneepath drama hindi-language, bollywo...
                              ...                        
6398    2018 2 laila majnu romanc hindi-language, boll...
6399    2018 3 veer di wed comedi hindi-language, boll...
6400    2024 1 paw patrol holiday fireplac kid kid mus...
6401    2019 4 notebook drama hindi-language, bollywoo...
6402    2018 4 loveyatri romanc hindi-language, bollyw...
Name: AllWords, Length: 3767, dtype: object

In [182]:
stemmed_vectors = cv.fit_transform(data['AllWords']).toarray()

In [184]:
print(stemmed_vectors)
print(stemmed_vectors.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(3767, 3000)


In [185]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(stemmed_vectors)

In [186]:
def recommend(movie):
    movie_index = data[data['Title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(data.iloc[i[0]].Title)

In [190]:
recommend('The Addams Family')

Addams Family Values
Deck the Halls
The Intern
The Bubble
Jackass 4.5
